// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/formance-go-sdk/pkg/models/shared"
	"net/http"
)

type ConnectorsStripeTransferResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	StripeTransferResponse *shared.StripeTransferResponse
}
