// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/formance-go-sdk/pkg/models/shared"
	"net/http"
)

type CreateScopeResponse struct {
	ContentType string
	// Created scope
	CreateScopeResponse *shared.CreateScopeResponse
	StatusCode          int
	RawResponse         *http.Response
}
