// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/formance-go-sdk/pkg/models/shared"
	"net/http"
)

type GetFlowRequest struct {
	// The flow id
	FlowID string `pathParam:"style=simple,explode=false,name=flowId"`
}

func (o *GetFlowRequest) GetFlowID() string {
	if o == nil {
		return ""
	}
	return o.FlowID
}

type GetFlowResponse struct {
	ContentType string
	// General error
	Error *shared.Error
	// The workflow
	GetWorkflowResponse *shared.GetWorkflowResponse
	StatusCode          int
	RawResponse         *http.Response
}

func (o *GetFlowResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetFlowResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetFlowResponse) GetGetWorkflowResponse() *shared.GetWorkflowResponse {
	if o == nil {
		return nil
	}
	return o.GetWorkflowResponse
}

func (o *GetFlowResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetFlowResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
