// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/formance-go-sdk/pkg/models/shared"
	"net/http"
)

type GetFlowRequest struct {
	// The flow id
	FlowID string `pathParam:"style=simple,explode=false,name=flowId"`
}

type GetFlowResponse struct {
	ContentType string
	// General error
	Error *shared.Error
	// The workflow
	GetWorkflowResponse *shared.GetWorkflowResponse
	StatusCode          int
	RawResponse         *http.Response
}
