// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/formance-go-sdk/pkg/models/shared"
	"net/http"
)

type GetWorkflowOccurrenceRequest struct {
	// The flow id
	FlowID string `pathParam:"style=simple,explode=false,name=flowId"`
	// The occurrence id
	RunID string `pathParam:"style=simple,explode=false,name=runId"`
}

type GetWorkflowOccurrenceResponse struct {
	ContentType string
	// General error
	Error *shared.Error
	// The workflow occurrence
	GetWorkflowOccurrenceResponse *shared.GetWorkflowOccurrenceResponse
	StatusCode                    int
	RawResponse                   *http.Response
}
