// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/formance-go-sdk/pkg/models/shared"
	"net/http"
)

type GetWorkflowOccurrenceRequest struct {
	// The flow id
	FlowID string `pathParam:"style=simple,explode=false,name=flowId"`
	// The occurrence id
	RunID string `pathParam:"style=simple,explode=false,name=runId"`
}

func (o *GetWorkflowOccurrenceRequest) GetFlowID() string {
	if o == nil {
		return ""
	}
	return o.FlowID
}

func (o *GetWorkflowOccurrenceRequest) GetRunID() string {
	if o == nil {
		return ""
	}
	return o.RunID
}

type GetWorkflowOccurrenceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// General error
	Error *shared.Error
	// The workflow occurrence
	GetWorkflowOccurrenceResponse *shared.GetWorkflowOccurrenceResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetWorkflowOccurrenceResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetWorkflowOccurrenceResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *GetWorkflowOccurrenceResponse) GetGetWorkflowOccurrenceResponse() *shared.GetWorkflowOccurrenceResponse {
	if o == nil {
		return nil
	}
	return o.GetWorkflowOccurrenceResponse
}

func (o *GetWorkflowOccurrenceResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetWorkflowOccurrenceResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
