// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/formance-go-sdk/pkg/models/shared"
	"net/http"
)

type ListAllConnectorsResponse struct {
	// OK
	ConnectorsResponse *shared.ConnectorsResponse
	ContentType        string
	StatusCode         int
	RawResponse        *http.Response
}
