// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/formance-go-sdk/pkg/models/shared"
	"net/http"
)

type ListFlowsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// General error
	Error *shared.Error
	// List of workflows
	ListWorkflowsResponse *shared.ListWorkflowsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListFlowsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListFlowsResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *ListFlowsResponse) GetListWorkflowsResponse() *shared.ListWorkflowsResponse {
	if o == nil {
		return nil
	}
	return o.ListWorkflowsResponse
}

func (o *ListFlowsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListFlowsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
