// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/formance-go-sdk/pkg/models/shared"
	"net/http"
)

type RunWorkflowRequest struct {
	RequestBody map[string]string `request:"mediaType=application/json"`
	// The flow id
	FlowID string `pathParam:"style=simple,explode=false,name=flowId"`
	// Wait end of the workflow before return
	Wait *bool `queryParam:"style=form,explode=true,name=wait"`
}

type RunWorkflowResponse struct {
	ContentType string
	// General error
	Error *shared.Error
	// The workflow occurrence
	RunWorkflowResponse *shared.RunWorkflowResponse
	StatusCode          int
	RawResponse         *http.Response
}
