// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type Attempt struct {
	Config         *WebhooksConfig `json:"config,omitempty"`
	CreatedAt      *time.Time      `json:"createdAt,omitempty"`
	ID             *string         `json:"id,omitempty"`
	NextRetryAfter *time.Time      `json:"nextRetryAfter,omitempty"`
	Payload        *string         `json:"payload,omitempty"`
	RetryAttempt   *int64          `json:"retryAttempt,omitempty"`
	Status         *string         `json:"status,omitempty"`
	StatusCode     *int64          `json:"statusCode,omitempty"`
	UpdatedAt      *time.Time      `json:"updatedAt,omitempty"`
	WebhookID      *string         `json:"webhookID,omitempty"`
}

func (o *Attempt) GetConfig() *WebhooksConfig {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *Attempt) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *Attempt) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Attempt) GetNextRetryAfter() *time.Time {
	if o == nil {
		return nil
	}
	return o.NextRetryAfter
}

func (o *Attempt) GetPayload() *string {
	if o == nil {
		return nil
	}
	return o.Payload
}

func (o *Attempt) GetRetryAttempt() *int64 {
	if o == nil {
		return nil
	}
	return o.RetryAttempt
}

func (o *Attempt) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *Attempt) GetStatusCode() *int64 {
	if o == nil {
		return nil
	}
	return o.StatusCode
}

func (o *Attempt) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *Attempt) GetWebhookID() *string {
	if o == nil {
		return nil
	}
	return o.WebhookID
}
