// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Balance struct {
	Name string `json:"name"`
}

func (o *Balance) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
