// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BankingCircleConfig struct {
	AuthorizationEndpoint string `json:"authorizationEndpoint"`
	Endpoint              string `json:"endpoint"`
	Password              string `json:"password"`
	Username              string `json:"username"`
}

func (o *BankingCircleConfig) GetAuthorizationEndpoint() string {
	if o == nil {
		return ""
	}
	return o.AuthorizationEndpoint
}

func (o *BankingCircleConfig) GetEndpoint() string {
	if o == nil {
		return ""
	}
	return o.Endpoint
}

func (o *BankingCircleConfig) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *BankingCircleConfig) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}
