// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ConfigResponse - Config created successfully.
type ConfigResponse struct {
	Data interface{} `json:"data"`
}
