// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConfigChangeSecret struct {
	Secret *string `json:"secret,omitempty"`
}

func (o *ConfigChangeSecret) GetSecret() *string {
	if o == nil {
		return nil
	}
	return o.Secret
}
