// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ConnectorEnum - The name of the connector.
type ConnectorEnum string

const (
	ConnectorEnumStripe        ConnectorEnum = "STRIPE"
	ConnectorEnumDummyPay      ConnectorEnum = "DUMMY-PAY"
	ConnectorEnumWise          ConnectorEnum = "WISE"
	ConnectorEnumModulr        ConnectorEnum = "MODULR"
	ConnectorEnumCurrencyCloud ConnectorEnum = "CURRENCY-CLOUD"
	ConnectorEnumBankingCircle ConnectorEnum = "BANKING-CIRCLE"
)
