// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateWalletRequest struct {
	// Custom metadata to attach to this wallet.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Name     string                 `json:"name"`
}
