// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreditWalletRequest struct {
	Amount Monetary `json:"amount"`
	// The balance to credit
	Balance *string `json:"balance,omitempty"`
	// Metadata associated with the wallet.
	Metadata  map[string]interface{} `json:"metadata,omitempty"`
	Reference *string                `json:"reference,omitempty"`
	Sources   []interface{}          `json:"sources"`
}
