// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DebitWalletRequest struct {
	Amount      Monetary    `json:"amount"`
	Balances    []string    `json:"balances,omitempty"`
	Description *string     `json:"description,omitempty"`
	Destination interface{} `json:"destination,omitempty"`
	// Metadata associated with the wallet.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Set to true to create a pending hold. If false, the wallet will be debited immediately.
	Pending *bool `json:"pending,omitempty"`
}
