// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/formance-go-sdk/pkg/utils"
)

type Error struct {
	errorCode    string `const:"VALIDATION" json:"errorCode"`
	ErrorMessage string `json:"errorMessage"`
}

func (e Error) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Error) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Error) GetErrorCode() string {
	return "VALIDATION"
}

func (o *Error) GetErrorMessage() string {
	if o == nil {
		return ""
	}
	return o.ErrorMessage
}
