// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ListRunsResponseCursor struct {
	Data     []WorkflowOccurrence `json:"data"`
	HasMore  *bool                `json:"hasMore,omitempty"`
	Next     *string              `json:"next,omitempty"`
	PageSize int64                `json:"pageSize"`
	Previous *string              `json:"previous,omitempty"`
}

// ListRunsResponse - List of workflow occurrences
type ListRunsResponse struct {
	Cursor ListRunsResponseCursor `json:"cursor"`
}
