// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

type LogTypeEnum string

const (
	LogTypeEnumNewTransaction LogTypeEnum = "NEW_TRANSACTION"
	LogTypeEnumSetMetadata    LogTypeEnum = "SET_METADATA"
)

func (e LogTypeEnum) ToPointer() *LogTypeEnum {
	return &e
}

func (e *LogTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NEW_TRANSACTION":
		fallthrough
	case "SET_METADATA":
		*e = LogTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LogTypeEnum: %v", v)
	}
}

type Log struct {
	Data map[string]interface{} `json:"data"`
	Date time.Time              `json:"date"`
	Hash string                 `json:"hash"`
	ID   int64                  `json:"id"`
	Type LogTypeEnum            `json:"type"`
}
