// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Monetary struct {
	// The amount of the monetary value.
	Amount int64 `json:"amount"`
	// The asset of the monetary value.
	Asset string `json:"asset"`
}

func (o *Monetary) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *Monetary) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}
