// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaymentMetadata struct {
	Changelog *PaymentMetadataChangelog `json:"changelog,omitempty"`
	Key       string                    `json:"key"`
	Value     string                    `json:"value"`
}
