// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

type PaymentSchemeEnum string

const (
	PaymentSchemeEnumVisa       PaymentSchemeEnum = "visa"
	PaymentSchemeEnumMastercard PaymentSchemeEnum = "mastercard"
	PaymentSchemeEnumAmex       PaymentSchemeEnum = "amex"
	PaymentSchemeEnumDiners     PaymentSchemeEnum = "diners"
	PaymentSchemeEnumDiscover   PaymentSchemeEnum = "discover"
	PaymentSchemeEnumJcb        PaymentSchemeEnum = "jcb"
	PaymentSchemeEnumUnionpay   PaymentSchemeEnum = "unionpay"
	PaymentSchemeEnumSepaDebit  PaymentSchemeEnum = "sepa debit"
	PaymentSchemeEnumSepaCredit PaymentSchemeEnum = "sepa credit"
	PaymentSchemeEnumSepa       PaymentSchemeEnum = "sepa"
	PaymentSchemeEnumApplePay   PaymentSchemeEnum = "apple pay"
	PaymentSchemeEnumGooglePay  PaymentSchemeEnum = "google pay"
	PaymentSchemeEnumA2a        PaymentSchemeEnum = "a2a"
	PaymentSchemeEnumAchDebit   PaymentSchemeEnum = "ach debit"
	PaymentSchemeEnumAch        PaymentSchemeEnum = "ach"
	PaymentSchemeEnumRtp        PaymentSchemeEnum = "rtp"
	PaymentSchemeEnumUnknown    PaymentSchemeEnum = "unknown"
	PaymentSchemeEnumOther      PaymentSchemeEnum = "other"
)

func (e *PaymentSchemeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "visa":
		fallthrough
	case "mastercard":
		fallthrough
	case "amex":
		fallthrough
	case "diners":
		fallthrough
	case "discover":
		fallthrough
	case "jcb":
		fallthrough
	case "unionpay":
		fallthrough
	case "sepa debit":
		fallthrough
	case "sepa credit":
		fallthrough
	case "sepa":
		fallthrough
	case "apple pay":
		fallthrough
	case "google pay":
		fallthrough
	case "a2a":
		fallthrough
	case "ach debit":
		fallthrough
	case "ach":
		fallthrough
	case "rtp":
		fallthrough
	case "unknown":
		fallthrough
	case "other":
		*e = PaymentSchemeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentSchemeEnum: %s", s)
	}
}

type PaymentTypeEnum string

const (
	PaymentTypeEnumPayIn    PaymentTypeEnum = "PAY-IN"
	PaymentTypeEnumPayout   PaymentTypeEnum = "PAYOUT"
	PaymentTypeEnumTransfer PaymentTypeEnum = "TRANSFER"
	PaymentTypeEnumOther    PaymentTypeEnum = "OTHER"
)

func (e *PaymentTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "PAY-IN":
		fallthrough
	case "PAYOUT":
		fallthrough
	case "TRANSFER":
		fallthrough
	case "OTHER":
		*e = PaymentTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentTypeEnum: %s", s)
	}
}

type Payment struct {
	AccountID     string                 `json:"accountID"`
	Adjustments   []PaymentAdjustment    `json:"adjustments"`
	Asset         string                 `json:"asset"`
	CreatedAt     time.Time              `json:"createdAt"`
	ID            string                 `json:"id"`
	InitialAmount int64                  `json:"initialAmount"`
	Metadata      []PaymentMetadata      `json:"metadata"`
	Provider      ConnectorEnum          `json:"provider"`
	Raw           map[string]interface{} `json:"raw"`
	Reference     string                 `json:"reference"`
	Scheme        PaymentSchemeEnum      `json:"scheme"`
	Status        PaymentStatusEnum      `json:"status"`
	Type          PaymentTypeEnum        `json:"type"`
}
