// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaymentMetadata struct {
	Changelog *PaymentMetadataChangelog `json:"changelog,omitempty"`
	Key       string                    `json:"key"`
	Value     string                    `json:"value"`
}

func (o *PaymentMetadata) GetChangelog() *PaymentMetadataChangelog {
	if o == nil {
		return nil
	}
	return o.Changelog
}

func (o *PaymentMetadata) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *PaymentMetadata) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}
