// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/speakeasy-sdks/formance-go-sdk/pkg/utils"
	"time"
)

type PaymentMetadataChangelog struct {
	Timestamp time.Time `json:"timestamp"`
	Value     string    `json:"value"`
}

func (p PaymentMetadataChangelog) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentMetadataChangelog) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PaymentMetadataChangelog) GetTimestamp() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Timestamp
}

func (o *PaymentMetadataChangelog) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}
