// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaymentStatusEnum string

const (
	PaymentStatusEnumPending    PaymentStatusEnum = "PENDING"
	PaymentStatusEnumActive     PaymentStatusEnum = "ACTIVE"
	PaymentStatusEnumTerminated PaymentStatusEnum = "TERMINATED"
	PaymentStatusEnumFailed     PaymentStatusEnum = "FAILED"
)
