// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RunWorkflowResponse - The workflow occurrence
type RunWorkflowResponse struct {
	Data WorkflowOccurrence `json:"data"`
}
