// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RunWorkflowResponse struct {
	Data WorkflowOccurrence `json:"data"`
}

func (o *RunWorkflowResponse) GetData() WorkflowOccurrence {
	if o == nil {
		return WorkflowOccurrence{}
	}
	return o.Data
}
