// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TasksCursorCursor struct {
	Data     []interface{} `json:"data"`
	HasMore  bool          `json:"hasMore"`
	Next     *string       `json:"next,omitempty"`
	PageSize int64         `json:"pageSize"`
	Previous *string       `json:"previous,omitempty"`
}

// TasksCursor - OK
type TasksCursor struct {
	Cursor TasksCursorCursor `json:"cursor"`
}
