// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WalletsErrorResponseErrorCodeEnum string

const (
	WalletsErrorResponseErrorCodeEnumValidation WalletsErrorResponseErrorCodeEnum = "VALIDATION"
)

// WalletsErrorResponse - Error
type WalletsErrorResponse struct {
	ErrorCode    WalletsErrorResponseErrorCodeEnum `json:"errorCode"`
	ErrorMessage string                            `json:"errorMessage"`
}
